# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df1931330c5def1017d8492e87beb5d32fd72ad21cf8bb263beb6ed5d5310eb1e8ed51b96d2d5deb234215409613d18cfd6fdbe61159ba847dd6b0fc8f912019

test:
  secret_key_base: 712aa913ed4ba14717241a26d304e7bbdf9fc951030442d3604caef8d02e6cc6a2368f950e5ca4939784ac69d59cabdf125d7c10c56cb4e45a717c04faaa7d30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
